# Generated by Django 6.0.2 on 2026-02-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pokedexentry_sprite_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedexentry',
            name='evolucion_siguiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_evolucion', to='api.pokedexentry'),
        ),
        migrations.AddField(
            model_name='pokedexentry',
            name='nivel_evolucion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokedexentry',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
