"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- DETECCIÓN DE ENTORNO (PyInstaller / Electron) ---
if getattr(sys, 'frozen', False):
    # En producción (empaquetado): Se guarda  en la carpeta del usuario
    # Windows: C:\Users\TuUsuario\.miapp_data | Linux: ~/.mipoke_data
    USER_DATA_DIR = Path(os.path.expanduser('~')) / '.mipoke_data'
    USER_DATA_DIR.mkdir(exist_ok=True)
else:
    # En desarrollo: Guardamos en la carpeta del proyecto
    USER_DATA_DIR = BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jdw%hlqv_7vw$k#dk9u^ed5yic!k-*vve9-meo0n1f!1wvhcta'

# SECURITY WARNING: don't run with debug turned on in production!
# Será True en desarrollo y False cuando lo compiles con PyInstaller  not getattr(sys, 'frozen', False)
DEBUG = True

# Permitimos que Electron (que corre local) se conecte
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt', 
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': USER_DATA_DIR / 'db.sqlite3', 
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configuración de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Esta es la que usa Vue para autenticarse con el token JWT
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # Esta es la que usa Django para autenticarse en desarollo
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

from datetime import timedelta

# Configuración de vida de los tokens
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), #  Dura 1 hora
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),    # Puedes renovarla por 1 día
}

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


CORS_ALLOW_ALL_ORIGINS = True  
# Permitir credenciales (cookies/tokens)
CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = 'api.Usuario' # Usamos nuestro modelo de usuario personalizado

# Configuración para manejar archivos de medios (fotos de perfil)
MEDIA_URL = '/media/'
# Las fotos se guardarán junto a la base de datos
MEDIA_ROOT = USER_DATA_DIR / 'media'

# Asegurarnos de que la carpeta media exista cuando arranque
if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)