# Generated by Django 6.0.2 on 2026-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pokedexentry_tipo_secundario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedexentry',
            name='sprite_shiny_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pokemonusuario',
            name='es_shiny',
            field=models.BooleanField(default=False),
        ),
    ]
