# Generated by Django 6.0.2 on 2026-02-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pokedexentry_sprite_shiny_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonusuario',
            name='piedra_eterna',
            field=models.BooleanField(default=False),
        ),
    ]
