# Generated by Django 6.0.2 on 2026-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pokedexentry_evolucion_siguiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedexentry',
            name='tipo_secundario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
