# Generated by Django 6.0.2 on 2026-02-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pokemonusuario_piedra_eterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pomo_ciclos',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pomo_tiempo_descanso_largo',
            field=models.IntegerField(default=30),
        ),
    ]
